[project]
name = "satellites"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.141.1",
    "msgspec>=0.21.1",
    "numpy>=2.5.3",
    "python-multipart>=0.0.32",
    "uvicorn[standard]>=0.52.4",
]

[dependency-groups]
dev = [
    "ruff>=0.16.7",
]
